### ISSUE TITLE
Bernstein basis rescale

### ISSUE THREAD

**Issue by raaavioli** [mld2443/RealtimeSubdivisionSurfaces#1]
Hi, I don't know if you'll ever see this. But if you do I'd be happy if you could answer a question regarding your spline re-scaling.

`
float4 Spline(float t)
{
	float T0 = 2.0f + t;
	float T1 = 1.0f + t;
	float T2 = 0.0f + t;
	float T3 = 1.0f - t;
	float T4 = 2.0f - t;
	float T5 = 3.0f - t;

	return float4(	(T3 * T3 * T3),
					((T0 * T3 * T3) + (T1 * T3 * T4) + (T2 * T4 * T4)),
					((T1 * T1 * T3) + (T1 * T2 * T4) + (T2 * T2 * T5)),
					(T2 * T2 * T2) );
}
`

So you use this function instead of the traditional bernstein basis to remap the uv's to fit your grid. I'm personally trying to deal with a problem in an implementation related to this, and would be very happy to know which resource you used to find out this formula instead of the classic Bernstein Basis. Do you remember where you found this formula, or did you come up with it yourself?

**Comment by mld2443** [comment]
I am happy to help!

There are many things I'm proud of in this repo, but you have found the pièce de résistance.

This project was my chosen final project for a class I took 7 years ago in graduate school at Texas A&M. It was for CSCE 645 Geometric Modeling taught by the inimitable Dr. Scott Schaefer who is now head of the computer science department there. Looking at his faculty website, it appears he has not been able to offer this class again since, a fact that makes me sad. There were many classes I took at A&M, but this was by far my favorite.

I mention it because the slides for the class are still available here: https://people.engr.tamu.edu/schaefer/teaching/645_Fall2015/lectures.html

You'll notice that actually, all of my assignments are here on my github. Homework 1 is my [Curves repo](https://github.com/mld2443/Curves), homework 2 is [Diffuse](https://github.com/mld2443/Diffuse), the extra credit part of homework 3 is [Subdivision](https://github.com/mld2443/Subdivision), and homework 4 is [Simplify](https://github.com/mld2443/Simplify).

Back on topic, of particular interest to your question is the lecture regarding *Blossoming and B-splines*. I'm a little rusty (I haven't reviewed these slides in 7 years), but in them he describes the 'blossom' of a polynomial, (IIRC he didn't name them blossoms and said that he didn't much care for the pretentious name). It's a way to reparametrize the polynomial following certain invariants that is unique.

A point of pride for him at the time was that there was no Wikipedia page on blossoming, and that the connection between these curves and this technique was not that well known, (he practically challenged us to update it!). My implementation you see in the domain shader was worked out 100% from evaluating a degree 3 b-spline curve following his blossoming slides and the pyramid diagrams contained therein. It is a full expansion rather than relying on recursion/memoization as I did in [curve.h](https://github.com/mld2443/Curves/blob/master/Curves/curve.h).

I'd be happy to talk about it more, or hear what it is you're working on! I am quite fond of this topic and haven't revisited it in quite some time.

**Comment by raaavioli** [comment]
So happy that you were able to answer this. I’ll have a close look at your resources when I’m back home.

I managed to solve my own problem before I got your answer by evaluating a degree2 bspline in a very funky way, but blossoming will definitely be very helpful to have my solution more generalized and to be able to perform interpolation of larger chains of particles. 

The work I’m doing is for my master’s degree in CS with focus on computer graphics. The project has just begun and is about rendering smooth particle trails/ ribbons using hardware accelerated tessellation. So my idea is to create a system for drawing smooth ribbons based on a stream of simulated particles. I’ll implement the rendering using the tessellation pipeline as well as the new mesh shader pipeline, and compare those with respect to performance.  I will also investigate how culling methods can be used for adaptive LOD on such tessellated ribbons to increase performance. 

Your work really set out as a great point of reference. The main difference is that my implementation couldn’t really be limited to 4x4 patches, but would have to be more generalized and allow for any NxM patch where N is the width of the ribbon and M is the length of the b-spline. Particularly, I’m starting with the simple 2x3 case and just got that working today. :)

**Comment by mld2443** [comment]
Sounds like exciting work, I can see why you were interested in this project of mine, it does sound like the starting point of what you're looking to accomplish.

About the only feedback I can give is that for my mesh simulation, I far preferred the look of the Catmull-Rom splines to the b-splines, simply because the control points being part of the final mesh gave a more flowing appearance to the ripples. I'd recommend it if you're okay with the surface of the ribbons occasionally exceeding the convex hull of the control mesh.

If you end up publishing or posting that work, do let me know.
